FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

# Install dependencies (cached layer)
COPY pyproject.toml uv.lock README.md ./
RUN uv sync --frozen --no-dev --no-install-project

# Copy application code
COPY src/ src/
COPY alembic.ini .
# RUN uv sync --frozen --no-dev

EXPOSE 8000

CMD uv run alembic upgrade head && \
    uv run uvicorn connect4.api.app:app --host 0.0.0.0 --port 8000
